"""redesign_account_and_transaction_models

Revision ID: 356d11c8efb4
Revises: 3b9fb9f704a4
Create Date: 2026-08-10 11:33:17.913460

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "356d11c8efb4"
down_revision: str | Sequence[str] | None = "3b9fb9f704a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint(
        "transactions_batch_id_fkey", "transactions", type_="foreignkey"
    )
    op.drop_column("transactions", "batch_id")

    op.drop_table("balance_snapshots")  # тоже ссылалась на batches
    op.drop_table("batches")
    op.drop_table("account_keywords")
    op.drop_table("account_interests")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column(
            "institution_acc_name", sa.String(length=100), nullable=False
        ),
    )
    op.add_column(
        "accounts",
        sa.Column("institution", sa.String(length=20), nullable=False),
    )
    op.drop_column("accounts", "balance_updated_at")
    op.drop_column("accounts", "initial_balance")
    op.drop_column("accounts", "is_categorizable")
    op.drop_column("accounts", "account_type")
    op.drop_column("accounts", "current_balance")
    op.drop_column("accounts", "is_balance_tracked")
    op.add_column(
        "transactions",
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "transactions",
        sa.Column("completed_date", sa.DateTime(timezone=True), nullable=False),
    )
    op.alter_column(
        "transactions", "account_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "transactions",
        "merchant",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.drop_column("transactions", "description")
    op.drop_column("transactions", "date")
    op.drop_column("transactions", "raw_type")
    op.drop_column("transactions", "is_categorizable")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("batch_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "is_categorizable",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "raw_type",
            sa.VARCHAR(length=30),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "description",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        op.f("transactions_batch_id_fkey"),
        "transactions",
        "batches",
        ["batch_id"],
        ["id"],
    )
    op.alter_column(
        "transactions",
        "merchant",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "transactions", "account_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_column("transactions", "completed_date")
    op.drop_column("transactions", "start_date")
    op.add_column(
        "accounts",
        sa.Column(
            "is_balance_tracked",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "accounts",
        sa.Column(
            "current_balance",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "accounts",
        sa.Column(
            "account_type",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "accounts",
        sa.Column(
            "is_categorizable",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "accounts",
        sa.Column(
            "initial_balance",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "accounts",
        sa.Column(
            "balance_updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("accounts", "institution")
    op.drop_column("accounts", "institution_acc_name")
    op.create_table(
        "balance_snapshots",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("batch_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "balance",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "snapshot_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("balance_snapshots_account_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batches.id"],
            name=op.f("balance_snapshots_batch_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("balance_snapshots_pkey")),
    )
    op.create_table(
        "account_interests",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("year", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("month", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "amount",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("account_interests_account_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("account_interests_pkey")),
        sa.UniqueConstraint(
            "account_id",
            "year",
            "month",
            name=op.f("account_interests_account_id_year_month_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "account_keywords",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "keyword",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("account_keywords_account_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("account_keywords_pkey")),
        sa.UniqueConstraint(
            "account_id",
            "keyword",
            name=op.f("account_keywords_account_id_keyword_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "batches",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "upload_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "total_count", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "status", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column("account_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("batches_account_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("batches_pkey")),
    )
    # ### end Alembic commands ###
