"""add raw_data to transactions

Revision ID: 64e8f390a112
Revises: 45cd9dd90817
Create Date: 2026-08-29 14:56:47.255396

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64e8f390a112"
down_revision: str | Sequence[str] | None = "45cd9dd90817"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("raw_data", sa.JSON(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "raw_data")
    # ### end Alembic commands ###
