"""change match_keyword to string

Revision ID: 867459fabb58
Revises: 5ecce3539d66
Create Date: 2026-05-13 20:22:29.674066

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "867459fabb58"
down_revision: str | Sequence[str] | None = "5ecce3539d66"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column("match_keyword", sa.String(length=100), nullable=False),
    )
    op.drop_column("accounts", "match_keywords")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column(
            "match_keywords", sa.TEXT(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("accounts", "match_keyword")
    # ### end Alembic commands ###
