"""add raw_type to transactions

Revision ID: a097e92edde4
Revises: 867459fabb58
Create Date: 2026-05-13 20:46:45.524809

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a097e92edde4"
down_revision: str | Sequence[str] | None = "867459fabb58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("raw_type", sa.String(length=30), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "raw_type")
    # ### end Alembic commands ###
