"""update_users_table

Revision ID: b2654272dfbc
Revises: 299b97ac3d78
Create Date: 2026-03-18 20:07:23.873474

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2654272dfbc"
down_revision: str | Sequence[str] | None = "299b97ac3d78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("login", sa.String(length=30), nullable=False)
    )
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.create_unique_constraint(None, "users", ["login"])
    op.drop_column("users", "name")
    op.drop_column("users", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "email", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "name", sa.VARCHAR(length=15), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.create_unique_constraint(
        op.f("users_email_key"),
        "users",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("users", "login")
    # ### end Alembic commands ###
