"""replace dedup_hash with natural key constraint

Revision ID: bcca1c55be76
Revises: 64e8f390a112
Create Date: 2026-08-29 17:30:01.977791

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bcca1c55be76"
down_revision: str | Sequence[str] | None = "64e8f390a112"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("occurrence", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        op.f("transactions_dedup_hash_key"), "transactions", type_="unique"
    )
    op.create_unique_constraint(
        None,
        "transactions",
        ["account_id", "start_date", "merchant", "amount", "fee", "occurrence"],
    )
    op.drop_column("transactions", "dedup_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "dedup_hash",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "transactions", type_="unique")
    op.create_unique_constraint(
        op.f("transactions_dedup_hash_key"),
        "transactions",
        ["dedup_hash"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("transactions", "occurrence")
    # ### end Alembic commands ###
